import {GetStaticProps, GetServerSideProps} from 'next';
import Head from 'next/head'
import SsnList from '../components/ssn-list';
import DatePicker, {DEFAULT_DATE} from "../components/DatePicker";
import {useEffect, useState} from "react";
import {Gender, Ssn} from "../components/ssn-list/SsnList";

const URL_BASE = process.env.SERVER_ROOT;

const Home = (props: {
    list: []
}) => {
    const [date, setDate] = useState(DEFAULT_DATE);
    const [list, setList] = useState<Ssn[]>(props.list);

    useEffect(() => {
        const fetcher = async () => {
            const newList: Ssn[] = await fetch(`/api/ssn/${date}`)
                .then(r => r.json())
                .then(res => res)
            setList(newList);
        }
        fetcher();
    }, [date]);

    return (
        <div>
            <Head>
                <title>Fødselsnummer</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.svg"/>
            </Head>

            <main>
                <DatePicker
                    onChange={setDate}
                />
                <SsnList
                    list={list}
                    date={date}
                />
            </main>
        </div>
    )
}

export default Home

export const getStaticProps: GetStaticProps = async (context) => {
    const list: {}[] = await fetch(`${process.env.SERVER_PROTOCOL}://${process.env.SERVER_ROOT}/generate/${DEFAULT_DATE}`)
        .then(r => r.json())
        .then(res => res)

    return {
        props: {
            list
        }
    }
}